### ISSUE TITLE
Example Line from readme.md fails

### ISSUE THREAD

**Issue by simpsus** [meaten/numerai_NN_example#1]
After forking/cloning with no additional work

(numerai) gbrecht@pop-os:~/github/numerai_NN_example$ python src/main.py --config_file config/mlp.yml --gpu 0
Traceback (most recent call last):
  File "src/main.py", line 679, in <module>
    main()
  File "src/main.py", line 662, in main
    cfg = load_config(args)
  File "/home/gbrecht/github/numerai_NN_example/src/utils.py", line 53, in load_config
    from default_param import _C as cfg
  File "/home/gbrecht/github/numerai_NN_example/src/default_param.py", line 67, in <module>
    _C.SOLVER.AUG = None
  File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/site-packages/yacs/config.py", line 155, in __setattr__
    _assert_with_logging(
  File "/home/gbrecht/miniconda3/envs/numerai/lib/python3.8/site-packages/yacs/config.py", line 521, in _assert_with_logging
    assert cond, msg
AssertionError: Invalid type <class 'NoneType'> for key AUG; valid types = {<class 'list'>, <class 'tuple'>, <class 'int'>, <class 'bool'>, <class 'str'>, <class 'float'>}

**Comment by simpsus** [comment]
After poking around a bit it seems that  "None" is not accepted as a value. Setting the AUG to '' makes the script proceed

**Comment by meaten** [comment]
Thanks for your feedback!
I forgot to remove the parameter that is not functional!
I fixed it:)
